Baseofsite/app/views/members_views.py
from flask import Blueprint, redirect, render_template, request, url_for
from flask_user import current_user, login_required
from app import db, babel
from app.models.user_models import UserProfileForm
from flask import current_app as app
import gettext

members_blueprint = Blueprint('members', __name__, template_folder='templates')


@babel.localeselector
def get_locale():
    translations = [str(translation) for translation in
                    babel.list_translations()]
    return request.accept_languages.best_match(translations)


def set_lang(lang):
    i18n_dir = app.config['BABEL_TRANSLATION_DIRECTORIES']
    gettext.install('lang', i18n_dir)
    trans_file = i18n_dir + lang + '/LC_MESSAGES/flask_user'
    tr = gettext.translation(trans_file, 'locale',  languages=[lang])
    tr.install(True)
    app.jinja_env.install_gettext_translations(tr)


@members_blueprint.before_app_request
def before_request():
    lang = get_locale()
    lang = lang if lang else app.config['BABEL_DEFAULT_LOCALE']
    set_lang(lang)

    if request.path.startswith('/admin'):
        if current_user.is_authenticated:
            if not current_user.has_role("admin"):
                return redirect(url_for('user.logout'))
        else:
            return redirect(url_for('user.login'))


@members_blueprint.route('/members/')
@login_required
def member_page():
    return render_template('pages/user_page.html')


@members_blueprint.route('/members/profile/', methods=['GET', 'POST'])
@login_required
def user_profile_page():
    # Initialize form
    # form = UserProfileForm(request.form, current_user)
    form = UserProfileForm()

    # Process valid POST
    if request.method == 'POST' and form.validate():
        # Copy form fields to user_profile fields
        form.populate_obj(current_user)

        # Save user_profile
        db.session.commit()

        # Redirect to home page
        return redirect(url_for('public.home_page'))

    # Process GET or invalid POST
    return render_template('pages/user_profile_page.html',
                           form=form)

Baseofsite/app/views/public_views.py
from flask import Blueprint, render_template

public_blueprint = Blueprint('public', __name__, template_folder='templates')


@public_blueprint.route('/')
def home_page():
    return render_template('pages/home_page.html')

Baseofsite/app/templates/layout.html
{% extends "bootstrap/base.html" %}
{% block title %}This is an example page{% endblock %}
{% import "bootstrap/fixes.html" as fixes %}
{% block head %}
  {{super()}}
  {{fixes.ie8()}}
{% endblock %}

{% block styles %}
  {{super()}}
  <link href="/static/css/global.css" rel="stylesheet">
{% endblock %}

{% block body %}

  {% block navbar %}
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">🐱 {{ user_manager.app_name }}</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="{{ url_for('public.home_page') }}">{{ _('Home Page') }}</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if current_user.is_authenticated %}
              <li><a href="{{ url_for('members.user_profile_page') }}"><span class="glyphicon glyphicon-user"></span> {{ _('Profile Page') }}</a></li>
              <li><a href="{{ url_for('user.logout') }}">{{ _('Sign out') }}</a></li>
            {% else %}
              <li><a href="{{ url_for('user.register') }}">{{ _('Register') }}</a></li>
              <li><a href="{{ url_for('user.login') }}"><span class="glyphicon glyphicon-log-in"></span>  {{ _('Sign in') }}</a></li>
            {% endif %}
          </ul>
          {% if current_user.is_authenticated %}
            {% if current_user.has_role("admin") %}
              <a  class="btn btn-danger navbar-btn"href="{{ url_for('admin.index') }}">{{ _('Admin') }}</a>
            {% endif %}
          {% endif %}
        </div><!--/.nav-collapse -->
      </div>
    </nav>

  {% endblock %}



  <div class="container">
    <div id="main-div" class="with-margins">

      {% import "bootstrap/utils.html" as utils %} {{ utils.flashed_messages(dismissible=True, container=False) }}
      {% block content %}{% endblock %}

    </div>
  </div>

  <footer class="footer">
    <div class="container">
      <p class="text-muted">&copy; <script type="text/javascript">var mdate = new Date(); document.write(mdate.getFullYear());</script>  {{ user_manager.app_name }}</p>
    </div>
  </footer>

  {% block scripts %}
    {{super()}}
  {% endblock %}



{% endblock %}